### ISSUE TITLE
请问，int()可以将带有字母的字符串转为int类型吗？

### ISSUE THREAD

**Issue by iamabug** [wanggang3333/MachineLearningInAction#1]
在chapter2/kNN.py中：
    `def file2matrix(filename):
    fr = open(filename)
    arrayLines = fr.readlines()
    numberOfLines = len(arrayLines)
    returnMat = zeros((numberOfLines,3))
    classLabelVector = []
    index = 0
    for line in arrayLines:
        line = line.strip()
        listFromLine = line.split('\t')
        returnMat[index,:] = listFromLine[0:3]
        classLabelVector.append(int(listFromLine[-1]))
        index += 1
    return returnMat, classLabelVector`

书中写的，得到的classLabelVector是一个由1、2、3组成的int型列表，但是我执行的时候，报的却是
ValueError：invalid literal for int() with base10: 'largeDoses'
我查看了python內建的int()和numpy的int()函数，好像没有这种功能，请问这是什么用法，谢谢。

**Comment by wanggang3333** [comment]
int()不可以将带有字母的字符串转为int

**Comment by iamabug** [comment]
恩，多谢。
